theme = "ananke"

title = "Cumstadística"
baseURL = "https://cumstadistica.github.io"
languageCode = "es-es"
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
pagerSize = 20

[languages]
[languages.es]
title = "Cumstadística"
weight = 1
contentDir = "content/es"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
  home = ['html', 'rss', 'json']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']


[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "El sitio web de Cumstadística"
custom_css = ["css/custom.css"]
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 20